name: Release

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
jobs:
  release_tag:
      runs-on: ubuntu-latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0
          
        - name: Set Release tag to env
          run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: OUTPUT RELEASE_TAG
          id: extag
          run: |
           echo $RELEASE_TAG5
           echo ${{ env.RELEASE_TAG }}
           tg=(${RELEASE_TAG//// })
           ETAG=${tg[1]}.0 >> $GITHUB_ENV
           echo $ETAG
          
         
        - name: Print etag
          run: |
            echo $ETAG
            git config user.name "Github Action Bot"
            git config user.email "<>"
            git tag -a v${ETAG} -m "tag version v${ETAG}" 
            git push -u origin v${ETAG}
            git tag
            
