name: Release

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
jobs:
  release_tag:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0
          
        - name: Set Release tag to env
          run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: OUTPUT RELEASE_TAG
          id: extag
          run: |
           echo $RELEASE_TAG5
           echo ${{ env.RELEASE_TAG }}
           tg=(${RELEASE_TAG//// })
           etag=${tg[1]}
           echo '::set-output name=tag::$(etag)
         
        - name: Print etag
          run: |
            echo ${{steps.extag.outputs.tag}}
           
           
